"""Add cascade for Course

Revision ID: 1e2990baf0bc
Revises: 80056e51ba2f
Create Date: 2023-08-08 16:34:41.742111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2990baf0bc'
down_revision: Union[str, None] = '80056e51ba2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_teacher_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['teacher_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_teacher_id_fkey', 'courses', 'users', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
