"""Add cascade for StudentCourse

Revision ID: 80056e51ba2f
Revises: 7d5e12663fab
Create Date: 2023-08-08 16:02:01.616014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80056e51ba2f'
down_revision: Union[str, None] = '7d5e12663fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_courses_course_id_fkey', 'student_courses', type_='foreignkey')
    op.drop_constraint('student_courses_student_id_fkey', 'student_courses', type_='foreignkey')
    op.create_foreign_key(None, 'student_courses', 'courses', ['course_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'student_courses', 'users', ['student_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_courses', type_='foreignkey')
    op.drop_constraint(None, 'student_courses', type_='foreignkey')
    op.create_foreign_key('student_courses_student_id_fkey', 'student_courses', 'users', ['student_id'], ['id'])
    op.create_foreign_key('student_courses_course_id_fkey', 'student_courses', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
