"""Add set  forurse

Revision ID: a7de906f6bfa
Revises: 6c538f73c132
Create Date: 2023-08-08 17:09:53.285071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7de906f6bfa'
down_revision: Union[str, None] = '6c538f73c132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_teacher_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_teacher_id_fkey', 'courses', 'users', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
